
skillMetadata:
  sections:
    - name: Webpage Homescreen
      fields:
        - type: label
          label: Provide a url to be used as your Mycroft Homescreen.
        - name: homepage_url
          type: text
          label: Homepage URL
          value: ""
        - name: refresh_frequency
          type: number
          label: Refresh frequency in seconds
          value: 600
